service: food

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
  stage: ${env:STAGE}
  timeout: 60
  environment:
    STAGE: ${env:STAGE}
    TELEGRAM_TOKEN_SUPPLY: ${env:TELEGRAM_TOKEN_SUPPLY}
    TELEGRAM_TOKEN_DEMAND: ${env:TELEGRAM_TOKEN_DEMAND}
    YANDEX_API_KEY: ${env:YANDEX_API_KEY}
    DB_CONNECTION_STRING: ${env:DB_CONNECTION_STRING}
    DB_NAME: ${env:DB_NAME}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:*
    Resource:
      - arn:aws:sqs:eu-central-1:${env:AWS_USER_ID}:send_message_${env:STAGE}.fifo
      - arn:aws:sqs:eu-central-1:${env:AWS_USER_ID}:super_send_${env:STAGE}.fifo


package:
  exclude:
    - local_data/**
    - node_modules/**
    - requirements/**
  include:
    - rest_food


custom:
  pythonRequirements:
    fileName: requirements/serverless.txt
    pythonBin: python
    useDownloadCache: true
    cacheLocation: .serverless/.cache

functions:
  supply:
    handler: rest_food.serverless.supply
    events:
      - http:
          path: supply/${env:BOT_PATH_KEY}/
          method: post
  demand:
    handler: rest_food.serverless.demand
    events:
      - http:
          path: demand/${env:BOT_PATH_KEY}/
          method: post

  send_message:
    handler: rest_food.serverless.send_message
    events:
      - sqs: arn:aws:sqs:eu-central-1:${env:AWS_USER_ID}:send_message_${env:STAGE}.fifo

  super_send:
    handler: rest_food.serverless.super_send
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:${env:AWS_USER_ID}:super_send_${env:STAGE}.fifo
          batchSize: 1


plugins:
  - serverless-python-requirements
